### ISSUE TITLE
The 08:11 from Uppsala to Arboga via Sthlm is not showing

### ISSUE THREAD

**Issue by fabjan** [jesperorb/sthlm-uppsala#2] opened 2023-01-19 23:17 UTC
Description
=========

ℹ️ **Just close this issue if you don't want feedback this way, I'll just choose a way to fix it in my fork if so. It's totally fine, I understand this is just a simple little utility** 👍 

It appears that only comparing the desired _departure location_ to the _location_ of an announcement (and then afterwards filtering on to-location or via-to-location) can miss some trains that don't include all information. The 08:11 stops at Uppsala and Stockholm and allows travel with Movingo. But Stockholm is not announced in the `ViaToLocation` so the app doesn't show it.

Details
=====

This query can be used for debugging:

```xml
<QUERY objecttype="TrainAnnouncement" schemaversion="1.3" orderby="AdvertisedTimeAtLocation">
    <FILTER>
        <AND>
            <EQ name="LocationSignature" value="U" />
            <EQ name="ActivityType" value="Avgang" />
            <GT name="AdvertisedTimeAtLocation" value="2023-01-20T08:10:00.000+01:00" />
            <LT name="AdvertisedTimeAtLocation" value="2023-01-20T08:15:00.000+01:00" />
        </AND>
    </FILTER>
</QUERY>
```

It gives a response (using no "include" projection) containing the following train announcement:

```json
{
  "ActivityId": "1500adde-f75d-3909-08da-ef867f2d5fd2",
  "ActivityType": "Avgang",
  "Advertised": true,
  "AdvertisedTimeAtLocation": "2023-01-20T08:11:00.000+01:00",
  "AdvertisedTrainIdent": "919",
  "Booking": [
    "Hela tåget är obokat."
  ],
  "Canceled": false,
  "Deleted": false,
  "EstimatedTimeIsPreliminary": false,
  "FromLocation": [
    {
      "LocationName": "U",
      "Priority": 1,
      "Order": 0
    }
  ],
  "InformationOwner": "Mälardalstrafik AB",
  "LocationSignature": "U",
  "ModifiedTime": "2023-01-10T04:22:53.491Z",
  "NewEquipment": 0,
  "OtherInformation": [
    "Stannar ej vid Märsta.",
    "Buss ers. Eskilstuna - Arboga.",
    "Movingo gäller."
  ],
  "PlannedEstimatedTimeAtLocationIsValid": false,
  "ProductInformation": [
    "Mälartåg"
  ],
  "ScheduledDepartureDateTime": "2023-01-20T00:00:00.000+01:00",
  "TechnicalTrainIdent": "919",
  "ToLocation": [
    {
      "LocationName": "Arb",
      "Priority": 1,
      "Order": 0
    }
  ],
  "TrackAtLocation": "8",
  "TrainComposition": [
    "Långt tåg."
  ],
  "TypeOfTraffic": "Tåg",
  "WebLink": "https://malartag.se/",
  "WebLinkName": "Mälartåg Kundservice"
}
```

The code in api/index.ts cannot see that this train also can be taken from `U` to `Cst`, because the announcement has no `ViaToLocation`.

Perhaps this is a bug in the data Mälartåg publishes? I do believe the data on the displays at the station show the train stopping in Sthlm, so not sure how they integrate this. Or perhaps it is expected one should combine all announcements for a given train to find this (I have never built a trip planner). Using the SJ App on my phone to plan a trip in the morning from U to Cst it shows train 919.

A Possible Solution
==============

Note: This example is departing from Uppsala and arriving in Stockholm, but there might be trains the other way that have similar problems with the `ViaToLocation` attribute.

Finding the Arboga train could be done by (pseudo query) `(Location=U && (ToLocation==Cst || ViaToLocation==Cst)) || (Location=Cst && (FromLocation==U || ViaFromLocation==U))`. I.e. move some more filtering up into the API request, and lookin for either of `{Location, ToLocation}` or `{FromLocation,Location}` combination (or the Via variants).

The announcements found tying U to Cst will then be for the train arriving at `Cst` (because the announcement data for location U has no data at all about Cst), so the train ident (919) would need to be used to go back and find announcements for the same train with location `U` to show the right time for departure. I think this requires an extra API call unless we make the first API call include _all_ departures from U regardless of the other information (because it is not until we have looked at the Cst arrivals we can identify the relevant U departures).

**Comment by jesperorb** [comment] 2023-01-21 09:12
Thank you for the detailed report, I will look into it :)

**Comment by fabjan** [comment] 2023-01-30 06:38
I noticed some other trains destined for Arboga are showing up in the App, but not all. 10:11 is missing, but 09:11 is there, and e.g. 11:11, 19:11.

Perhaps the data is just wrong and the real fix is for Mälartåg (or Trafikverket?) to update it.

**Comment by jesperorb** [comment] 2023-01-31 11:33
> I noticed some other trains destined for Arboga are showing up in the App, but not all. 10:11 is missing, but 09:11 is there, and e.g. 11:11, 19:11.
> 
> Perhaps the data is just wrong and the real fix is for Mälartåg (or Trafikverket?) to update it.

Yes, I noticed this as well. Train 17 from Falun is the same. I have a solution locally that I will push later, but that is a manual fix. 

The problem is inconsistent data from Trafikverket, and not only Mälartåg, SJ has missing data as well.

The real fix is probably to do as you were saying, modifying so that the API-query is smarter. I am not particularly savvy with this xml based query structure. I will have a go at it after work but I can't make any guarantee that I will produce a good enough query 😅

**Comment by jesperorb** [comment] 2023-02-01 19:04
@fabjan Didn't have much luck creating a smarter query unfortunately.

Tho I pushed a fix for adding certain trains manually so the ones we've found will show up.

**Comment by fabjan** [comment] 2023-02-02 07:27
When I get home today I'll share the code I used while experimenting with their API trying to even find out what was happening. I maybe have half a solution in there you can look at to see if it fits.

**Closed as completed** 2023-02-05 17:41 UTC
